version: '3.7'

services:
  nginx:
    ports:
      - ${EXTERNAL_PORT}:${NGINX_PORT}
  main:
    build:
      target: production
    command: npm run start:prod
    environment:
      FRONTENT_URL: ${FRONTEND_URL}
  postgres:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
