version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - ${EXTERNAL_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
    depends_on:
      - main
  main:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    environment:
      FRONTENT_URL: ${FRONTEND_URL}
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
