version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:6.2.6
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:14.0
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_DB: ${POSTGRES_DB:-test}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
