version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
    depends_on:
      - main
  main:
    image: toadslop/tapo-back
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
